
WindowManager:

<WindowManager>:
    MainWindow:
    SecondWindow:


<MainWindow>:
    name:"first"

    GridLayout: 
        cols: 1
        Label:
            id: bt1
            text:"Hello Kivy"
        Button:
            id: ba1
            text:"Send MSG"

<SecondWindow>:
    name:"second"
    
    GridLayout:
        cols: 1
        Label:
            id: bt1
            text:"Hello User"
        Button:
            id: bb1
            text:"Back"